package ProjectEuler;
/*
Author : Ashutosh Kumar
Date : 10/04/20 
Email : ashutoshkumardbms@gmail.com
Published on : 2020,April,Friday
Description : Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million,
find the sum of the even-valued terms.

*/

public class Question2 {
    public static void main(String[] args)
    {
        int a = 1, b = 2, c = 0, sum = 2;
        while (c <= 4000000)
        {
            c = a + b;
            System.out.println("1st Loop entry "+a+"  "+b);
            System.out.println(c);
            if ((c & 1) == 0) {
                sum = sum + c;
            }

            a = b;
            b = c;
            System.out.println("After swap"+a+"  "+b);
        }
        System.out.println(sum);
    }
}
