package ProjectEuler;

/*
Author : Ashutosh Kumar
Date : 15/04/20 
Email : ashutoshkumardbms@gmail.com
Published on : 2020,April,Wednesday
Description :
The sequence of triangle numbers is generated by adding the natural numbers.
So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

public class Question12 {
    public static void main(String[] args) {
        long counter = 0, sum = 0;
        for (int next = 10; ; next++) {
            // sum of numbers using n(n+1)/2 formula
            sum = (next * (next + 1)) / 2;

            if (countFactors(sum) > 500) {
                // if factor is > 500 then break;
                System.out.println(sum);
                break;
            }
        }
    }

    static int countFactors(long num) {
        int count = 0;
        //walking until square root
        for (long i = 1; i <= Math.sqrt(num); i++) {
            if (num % i == 0)
                count += 2;
        }
        return count;
    }
}
